# Generated by scripts/release-cli in homegrownsw/byway, from
# server/cmd/byway/homebrew/byway.rb.tmpl. Do not edit by hand — the next release
# overwrites this file.
#
# The rendered formula is not committed to the source repo: it pins the sha256 of
# an archive that only exists once a release is published, so a copy there would
# be stale between every release and correct in none.
#
# The archive is a signed, notarized universal (arm64 + x86_64) binary, so there
# is one url/sha256 rather than a per-architecture branch.
class Byway < Formula
  desc "Read-only desktop client for your Byway location history"
  homepage "https://byway.place"
  version "2026.1"
  url "https://github.com/homegrownsw/homebrew-byway/releases/download/byway-v2026.1/byway-2026.1-macos-universal.zip"
  sha256 "b458cf0e49ca5654d185ff5f955b2e94dfa5200aa7be09e79aa44f14de6ff243"
  # Byway is a closed-source product; the binary is redistributable, the source is not.
  license :cannot_represent

  # Keychain-backed keys and a signed Mach-O binary — macOS only for now
  # (a Linux build is a tracked follow-up, see the CLI's README).
  depends_on :macos

  def install
    bin.install "byway"
  end

  test do
    assert_match "byway #{version}", shell_output("#{bin}/byway version")
  end
end
